project:
  repo_owner: dwhswenson
  repo_name: plugcli
  project_name: plugcli

repo:
  release-branches:
    - stable
  release-tag: "v{BASE_VERSION}"

# writing release notes
notes:
  labels:
    - label: enhancement
      heading: New features
    - label: bugfix
      heading: Bugs fixed
    - label: misc PR
      heading: Miscellaneous improvements

  standard-contributors:
    - dwhswenson

release-check:
  versions:
    - setup-cfg
    #- getattr: plugcli.version.version

env:
  package-import-name: "plugcli"
  dry: ""
