project:
  repo_owner: dwhswenson
  repo_name: plugcli
  project_name: plugcli

repo:
  release-branches:
    - stable
  release-tag: "v{BASE_VERSION}"

release-check:
  versions:
    - setup-cfg
    #- getattr: plugcli.version.version

env:
  package-import-name: "plugcli"
  dry: ""
